# Generated by Django 2.1.2 on 2018-10-17 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_estoque', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produto_variacao', to='kamisetas_app.VariacaoProduto'),
        ),
    ]
