# Generated by Django 2.1.2 on 2018-10-19 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kamisetas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('excluido', models.BooleanField(default=False)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_carrihno', to='kamisetas_app.CarrinhoUser')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_forma_pagamento', to='kamisetas_app.FormaPagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluido', models.BooleanField(default=False)),
                ('pessoa_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_variacao', to='kamisetas_app.VariacaoProduto'),
        ),
        migrations.AddField(
            model_name='carrinhouser',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_usuario', to='kamisetas_app.Usuario'),
        ),
    ]
