# Generated by Django 2.1.2 on 2018-10-19 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamisetas_app', '0002_auto_20181019_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_produto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('excluido', models.BooleanField(default=False)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_carrinho_carrinho', to='kamisetas_app.CarrinhoUser')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_carrinho_produto', to='kamisetas_app.Produto')),
            ],
        ),
    ]
