# Generated by Django 2.1.2 on 2018-10-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamisetas_app', '0003_produtocarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_variacao', to='kamisetas_app.VariacaoProduto'),
        ),
    ]
