from kamisetas_app.views.cadastros.produto_carrinho import ProdutoCarrinhoCreateView
from kamisetas_app.views.cadastros.produto_create import ProdutoCreateView
from kamisetas_app.views.cadastros.realizar_compra import RealizarCompraCreateView
from kamisetas_app.views.cadastros.usuario_create import UsuarioCreateView
from kamisetas_app.views.cadastros.variacao_produto_create import VariacaoProdutoCreateView